name: CD Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - 'dashboard/**'

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name handytec-cluster

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install devops-app ./charts/devops-app \
            -f ./charts/devops-app/values-prod.yaml \
            --set image.tag=${{ github.sha }} \
            --namespace production --create-namespace
